### ISSUE TITLE
Verbose option (-v) does not work as expected, responds with version instead

### ISSUE THREAD

**Issue by gspannu** [ameshkov/godnsbench#1]
-v reports version number rather than verbose
However, --verbose works as expected.

Command:
`godnsbench -a tls://dns.google -p 1 -c 1 --verbose`

Response _as expected_
```
2022/08/19 00:31:43 22033#1 [info] Run godnsbench with the following configuration
2022/08/19 00:31:43 22033#1 [info] Address: tls://dns.google
.....
2022/08/19 00:31:43 22033#1 [info] Query timeout: 10 seconds
2022/08/19 00:31:44 22033#1 [info] Errors count: 0
```

However, the same command with -v option

Sample execution:
`godnsbench -a tls://dns.google -p 1 -c 1 -v`

Response
`godnsbench version: 1.0`

**Comment by ameshkov** [comment]
Oh, yeah, missed that.

**Comment by gspannu** [comment]
Thanks.
