### ISSUE TITLE
Ошибка invalid argument при тестировании DoH3

### ISSUE THREAD

**Issue by ammnt** [ameshkov/godnsbench#2]
Приветствую,

получаю ошибку invalid argument при попытке тестирования DoH3 на разных серверах:

❯ godnsbench -a h3://dns.google/dns-query -p 1 -c 1 -v -q example.net        
2022/10/08 23:07:39 11367#1 [info] Run godnsbench with the following configuration:
{
    "Address": "h3://dns.google/dns-query",
    "Connections": 1,
    "Query": "example.net",
    "Timeout": 10,
    "Rate": 0,
    "QueriesCount": 1,
    "Verbose": true,
    "LogOutput": ""
}
2022/10/08 23:07:39 11367#35 [info] Starting the test and running 1 connections in parallel
2022/10/08 23:07:39 11367#36 [debug] github.com/AdguardTeam/dnsproxy/upstream.lookup(): successfully finished lookup for dns.google in 40.28775ms using . Result : [{8.8.4.4 } {8.8.8.8 }]
2022/10/08 23:07:39 11367#36 [debug] github.com/AdguardTeam/dnsproxy/upstream.(*bootstrapper).createDialContext.func1(): Dialing to 8.8.4.4:443
2022/10/08 23:07:39 11367#36 [debug] github.com/AdguardTeam/dnsproxy/upstream.(*bootstrapper).createDialContext.func1(): dialer has successfully initialized connection to 8.8.4.4:443 in 170.917µs
2022/10/08 23:07:39 11367#36 [debug] using HTTP/3 for this upstream: QUIC was faster
2022/10/08 23:07:39 11367#36 [debug] https://dns.google:443/dns-query: sending request A example.net.
2022/10/08 23:07:39 11367#36 [debug] https://dns.google:443/dns-query: response: requesting https://dns.google:443/dns-query: Get "https://dns.google:443/dns-query?dns=AAABAAABAAAAAAAAB2V4YW1wbGUDbmV0AAABAAE": INTERNAL_ERROR: write udp [::]:63451->8.8.4.4:443: sendto: invalid argument
2022/10/08 23:07:39 11367#36 [debug] error occurred: requesting https://dns.google:443/dns-query: Get "https://dns.google:443/dns-query?dns=AAABAAABAAAAAAAAB2V4YW1wbGUDbmV0AAABAAE": INTERNAL_ERROR: write udp [::]:63451->8.8.4.4:443: sendto: invalid argument
2022/10/08 23:07:39 11367#35 [info] Finished running all connections
2022/10/08 23:07:39 11367#1 [info] The test has finished.
2022/10/08 23:07:39 11367#1 [info] The test results are:
2022/10/08 23:07:39 11367#1 [info] Elapsed: 246.688667ms
2022/10/08 23:07:39 11367#1 [info] Average QPS: 4.053178
2022/10/08 23:07:39 11367#1 [info] Processed queries: 0
2022/10/08 23:07:39 11367#1 [info] Average per query: 246.78175ms
2022/10/08 23:07:39 11367#1 [info] Errors count: 1

❯ godnsbench -a h3://cloudflare-dns.com/dns-query -p 1 -c 1 -v -q example.net
2022/10/08 23:07:54 11389#1 [info] Run godnsbench with the following configuration:
{
    "Address": "h3://cloudflare-dns.com/dns-query",
    "Connections": 1,
    "Query": "example.net",
    "Timeout": 10,
    "Rate": 0,
    "QueriesCount": 1,
    "Verbose": true,
    "LogOutput": ""
}
2022/10/08 23:07:54 11389#34 [info] Starting the test and running 1 connections in parallel
2022/10/08 23:07:54 11389#35 [debug] github.com/AdguardTeam/dnsproxy/upstream.lookup(): successfully finished lookup for cloudflare-dns.com in 44.242292ms using . Result : [{104.16.248.249 } {104.16.249.249 }]
2022/10/08 23:07:54 11389#35 [debug] github.com/AdguardTeam/dnsproxy/upstream.(*bootstrapper).createDialContext.func1(): Dialing to 104.16.248.249:443
2022/10/08 23:07:54 11389#35 [debug] github.com/AdguardTeam/dnsproxy/upstream.(*bootstrapper).createDialContext.func1(): dialer has successfully initialized connection to 104.16.248.249:443 in 164.709µs
2022/10/08 23:07:54 11389#35 [debug] using HTTP/3 for this upstream: QUIC was faster
2022/10/08 23:07:54 11389#35 [debug] https://cloudflare-dns.com:443/dns-query: sending request A example.net.
2022/10/08 23:07:54 11389#35 [debug] https://cloudflare-dns.com:443/dns-query: response: requesting https://cloudflare-dns.com:443/dns-query: Get "https://cloudflare-dns.com:443/dns-query?dns=AAABAAABAAAAAAAAB2V4YW1wbGUDbmV0AAABAAE": INTERNAL_ERROR: write udp [::]:64172->104.16.248.249:443: sendto: invalid argument
2022/10/08 23:07:54 11389#35 [debug] error occurred: requesting https://cloudflare-dns.com:443/dns-query: Get "https://cloudflare-dns.com:443/dns-query?dns=AAABAAABAAAAAAAAB2V4YW1wbGUDbmV0AAABAAE": INTERNAL_ERROR: write udp [::]:64172->104.16.248.249:443: sendto: invalid argument
2022/10/08 23:07:54 11389#34 [info] Finished running all connections
2022/10/08 23:07:54 11389#1 [info] The test has finished.
2022/10/08 23:07:54 11389#1 [info] The test results are:
2022/10/08 23:07:54 11389#1 [info] Elapsed: 247.522791ms
2022/10/08 23:07:54 11389#1 [info] Average QPS: 4.039541
2022/10/08 23:07:54 11389#1 [info] Processed queries: 0
2022/10/08 23:07:54 11389#1 [info] Average per query: 247.615666ms
2022/10/08 23:07:54 11389#1 [info] Errors count: 1

❯ godnsbench -a h3://1.1.1.1/dns-query -p 1 -c 1 -v -q example.net           
2022/10/08 23:08:12 11411#1 [info] Run godnsbench with the following configuration:
{
    "Address": "h3://1.1.1.1/dns-query",
    "Connections": 1,
    "Query": "example.net",
    "Timeout": 10,
    "Rate": 0,
    "QueriesCount": 1,
    "Verbose": true,
    "LogOutput": ""
}
2022/10/08 23:08:12 11411#20 [info] Starting the test and running 1 connections in parallel
2022/10/08 23:08:12 11411#21 [debug] github.com/AdguardTeam/dnsproxy/upstream.(*bootstrapper).createDialContext.func1(): Dialing to 1.1.1.1:443
2022/10/08 23:08:12 11411#21 [debug] github.com/AdguardTeam/dnsproxy/upstream.(*bootstrapper).createDialContext.func1(): dialer has successfully initialized connection to 1.1.1.1:443 in 139.75µs
2022/10/08 23:08:12 11411#21 [debug] using HTTP/3 for this upstream: QUIC was faster
2022/10/08 23:08:12 11411#21 [debug] https://1.1.1.1:443/dns-query: sending request A example.net.
2022/10/08 23:08:12 11411#21 [debug] https://1.1.1.1:443/dns-query: response: requesting https://1.1.1.1:443/dns-query: Get "https://1.1.1.1:443/dns-query?dns=AAABAAABAAAAAAAAB2V4YW1wbGUDbmV0AAABAAE": INTERNAL_ERROR: write udp [::]:49471->1.1.1.1:443: sendto: invalid argument
2022/10/08 23:08:12 11411#21 [debug] error occurred: requesting https://1.1.1.1:443/dns-query: Get "https://1.1.1.1:443/dns-query?dns=AAABAAABAAAAAAAAB2V4YW1wbGUDbmV0AAABAAE": INTERNAL_ERROR: write udp [::]:49471->1.1.1.1:443: sendto: invalid argument
2022/10/08 23:08:12 11411#20 [info] Finished running all connections
2022/10/08 23:08:12 11411#1 [info] The test has finished.
2022/10/08 23:08:12 11411#1 [info] The test results are:
2022/10/08 23:08:12 11411#1 [info] Elapsed: 203.623375ms
2022/10/08 23:08:12 11411#1 [info] Average QPS: 4.910268
2022/10/08 23:08:12 11411#1 [info] Processed queries: 0
2022/10/08 23:08:12 11411#1 [info] Average per query: 203.716958ms
2022/10/08 23:08:12 11411#1 [info] Errors count: 1

Спасибо.

**Comment by ameshkov** [comment]
@ammnt AdGuard блокирует HTTP/3 пока что:)

**Comment by ammnt** [comment]
@ameshkov, блин выключал вроде оба приложения... Да, сейчас завелось🥳
