### ISSUE TITLE
Cache busting queries

### ISSUE THREAD

**Issue by ignoramous** [ameshkov/godnsbench#3]
May be prudent to add queries that bust caches (both client-side and server-side) to gauge the actual recursive resolution time.

From a rudimentary profiler we wrote to test Node v Deno perf (in bash):

```bash
    prefix=$( dd if=/dev/urandom bs=20 count=20 status=none | tr -dc 'A-Z0-9' | xargs echo )
    # ex: JM7LBADPQGM7326MHWMYTNR09XBBGFKIWHVG6BQH6JK5QX103G4Q1H5SLYN.dnsleaktest.com
    domain="${prefix}.dnsleaktest.com"
    dohquery ${domain}
```
`dnsleaktest.com` can be substituted with any domain with wildcard DNS (like, `neverssl.com`, for example).

Ref: [serverless-dns/serverless-dns/run:L56](https://github.com/serverless-dns/serverless-dns/blob/270d1a3c232a38ed259fb4dabbcad9d68ce626f9/run).

**Comment by ameshkov** [comment]
You can now use something like that:
`godnsbench -a https://dns.google/dns-query -p 10 -c 1000 -t 1 -q {random}.example.net`
