### ISSUE TITLE
zsh: command not found: godnsbench

### ISSUE THREAD

**Issue by nferocious76** [ameshkov/godnsbench#6]
Installed using brew with no error during installation.
However, this does not seem to work while my other packages installed from brew works fine.

So I have re-updated my settings again adding this new settings: (I am using Intel Mac)
export PATH="/usr/local/bin:$PATH"

This still seems to fail with same issue: `zsh: command not found: godnsbench`

**Comment by ameshkov** [comment]
Try doing `brew link godnsbench`.

Brew puts the distr to `/usr/local/Cellar/godnsbench` by default and creates a symlink to the executable in `/usr/local/bin` so if you have it in PATH, it should be accessible.

If it is still not found, check the following:
1. Check that `godnsbench` has been installed to `/usr/local/Cellar/godnsbench`
2. Check that there is a symlink in `/usr/local/bin`
3. Check what `echo $PATH` shows in the terminal and whether it contains the path to `/usr/local/bin`
